# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbg < Formula
  desc "DBGorilla CLI -- sign in and connect Claude Code via MCP"
  homepage "https://dbgorilla.com"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.4/dbg-darwin-amd64"
      sha256 "7a127a6d1d111f62847471602b5e44e00200e7c7a488eb191452c5b0203d4d67"

      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.4/dbg-darwin-arm64"
      sha256 "88871bf75fe8249919bde39fdaf804e1a84cc7dae9eae48482c059132c74e528"

      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.4/dbg-linux-amd64"
      sha256 "1d907a0e12280e872f42ce1e5113c20f01605b7fe37069fd76d7d2078b6650da"
      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.4/dbg-linux-arm64"
      sha256 "a05340e1fa5f04b70781f09ddc582c6af3aa659219fae3746b626aff0c54ba20"
      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbg"
      end
    end
  end

  test do
    system "#{bin}/dbg", "version"
  end
end
