# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbgorilla < Formula
  desc "DBGorilla CLI -- sign in and connect Claude Code via MCP"
  homepage "https://dbgorilla.com"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.3.1/dbg-darwin-amd64"
      sha256 "151e17f6bea3bd1431e7a52921d9a28ec29a5142410e9adfc12b89a0e4b65980"

      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbgorilla"
        bin.install_symlink "dbgorilla" => "dbg"
        # Cobra's built-in `dbgorilla completion <shell>` already emits a valid
        # script for each shell; this Homebrew helper runs it and installs the
        # output to the right completions directory (bash/zsh/fish) so tab
        # completion works immediately after `brew install`, with no manual
        # `dbgorilla completion zsh > ...` step required.
        generate_completions_from_executable(bin/"dbgorilla", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.3.1/dbg-darwin-arm64"
      sha256 "04b42bed205dd4b7db181964c0aa9999b57d8402499cb51d36d4194006724341"

      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbgorilla"
        bin.install_symlink "dbgorilla" => "dbg"
        # Cobra's built-in `dbgorilla completion <shell>` already emits a valid
        # script for each shell; this Homebrew helper runs it and installs the
        # output to the right completions directory (bash/zsh/fish) so tab
        # completion works immediately after `brew install`, with no manual
        # `dbgorilla completion zsh > ...` step required.
        generate_completions_from_executable(bin/"dbgorilla", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.3.1/dbg-linux-amd64"
      sha256 "b48327b09d1ff1922971bc18ff9c2547e5dff13e3692e9fdff48b83867a05ad0"
      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbgorilla"
        bin.install_symlink "dbgorilla" => "dbg"
        # Cobra's built-in `dbgorilla completion <shell>` already emits a valid
        # script for each shell; this Homebrew helper runs it and installs the
        # output to the right completions directory (bash/zsh/fish) so tab
        # completion works immediately after `brew install`, with no manual
        # `dbgorilla completion zsh > ...` step required.
        generate_completions_from_executable(bin/"dbgorilla", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.3.1/dbg-linux-arm64"
      sha256 "30231a38079a092a5dd313940c1cd13c11f7424ddcaf769d460f3410a69cd2f7"
      define_method(:install) do
        bin.install Dir["dbg-*"].first => "dbgorilla"
        bin.install_symlink "dbgorilla" => "dbg"
        # Cobra's built-in `dbgorilla completion <shell>` already emits a valid
        # script for each shell; this Homebrew helper runs it and installs the
        # output to the right completions directory (bash/zsh/fish) so tab
        # completion works immediately after `brew install`, with no manual
        # `dbgorilla completion zsh > ...` step required.
        generate_completions_from_executable(bin/"dbgorilla", "completion")
      end
    end
  end

  test do
    system "#{bin}/dbgorilla", "version"
  end
end
