# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbgorilla < Formula
  desc "DBGorilla CLI -- sign in and connect Claude Code via MCP"
  homepage "https://dbgorilla.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-darwin-amd64"
      sha256 "9310046e8ff4d2319da646d914a09e8cce746ec52ae1ea081e728fb9617b41ef"

      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-darwin-arm64"
      sha256 "38d20e057a0019cb905746b9d768d8062b4e71f5dc1079a6653a98ae6f0ffc65"

      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-linux-amd64"
      sha256 "29c93f9683d17bb347449e797407e2bb4cd667feb5c6551cfffbf68f3ad1169c"
      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-linux-arm64"
      sha256 "690172142d6c8fb7513b353c45796400f3c3c1558803cbc8201d38c9d97636a1"
      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
  end

  test do
    system "#{bin}/dbgorilla", "version"
  end
end
