# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbgorilla < Formula
  desc "DBGorilla CLI -- sign in and connect Claude Code via MCP"
  homepage "https://dbgorilla.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-darwin-amd64"
      sha256 "9629f05eb1ae72705d086a525cf00c9c0069b68c7f70bf7d296e29f43a3d543f"

      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-darwin-arm64"
      sha256 "afd63e3acb2b73944c05f486aca0484ff8dffb227f86b8e964d05a4167c92948"

      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-linux-amd64"
      sha256 "2e64f008ff365dfe1ecced1e800ed34bbaa3169427110ddea918578f9af11f27"
      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbgorilla/dbgorilla-cli/releases/download/v0.1.0/dbgorilla-linux-arm64"
      sha256 "996f8dbd3856d62f4911e47e414626c50f9664869ca66c337a85b9d0ac4c06cd"
      define_method(:install) do
        bin.install Dir["dbgorilla-*"].first => "dbgorilla"
      end
    end
  end

  test do
    system "#{bin}/dbgorilla", "version"
  end
end
